name: UIPS-CI

on:
   push:
     branches: [master]
   pull_request:
     branches: [master]

jobs:
  PINN:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Formatting and sorting import
        run: |
          source .github/linters/formatting.sh
          format *.py true
          format utils true
      - name: Run pytest
        run: |
          python main_iterative.py tests/input_test
