name: UIPS-CI

on:
   push:
     branches: [main]
     paths-ignore:
        - '*.md'
        - 'README*'
        - 'LICENSE'
   pull_request:
     branches: [main]
     paths-ignore:
        - '*.md'
        - 'README*'
        - 'LICENSE'

jobs:
  UIPS:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        mpi: ['openmpi']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{matrix.mpi}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          pip install black
          pip install isort
          pip install codespell
          pip install pytest 
      - name: Formatting
        run: |
          source .github/linters/formatting.sh
          format . true
          codespell
      - name: Pytests
        run: |
          python -m pytest tests -v --disable-warnings
      - name: Parallel test
        run: |
          cd tests
          mpiexec -np 2 python main_from_input.py -i ../uips/inputs/input_test
