name: UIPS-CI

on:
   push:
     branches: [main]
   pull_request:
     branches: [main]

jobs:
  UIPS:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        mpi: ['openmpi']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{matrix.mpi}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Formatting
        run: |
          source .github/linters/formatting.sh
          format . true
          codespell
      - name: Normalizing flow test
        run: |
          python main_iterative.py -i tests/input_test
      - name: Bins test
        run: |
          python main_iterative.py -i tests/input_test_bins
      - name: Parallel normalizing flow test
        run: |
          mpiexec -np 2 python main_iterative.py -i tests/input_test
